In [167]:
import numpy as np
import os
import time
import datetime
import csv

In [76]:
#Descargo y limpio el archivo
os.system("bash limpiador.sh")

0

In [77]:
#Importo los datos
correr = np.genfromtxt("datoscorrer.csv",delimiter=",",names=True)

In [78]:
correr["lon"]

array([-74.07830811, -74.07826233, -74.07821655, ..., -74.08422852,
       -74.08422852, -74.08422852])

In [79]:
correr["lat"]

array([ 4.65095949,  4.65105486,  4.65120363, ...,  4.63229609,
        4.63229609,  4.63229609])

In [80]:
correr["elev"]

array([ 2604.,  2594.,  2572., ...,  2585.,  2585.,  2585.])

In [81]:
correr["time"]

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [82]:
correr["time"] = 1

In [83]:
correr["time"][0]

1.0

In [84]:
correr["time"]

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [154]:
a =np.loadtxt("datoscorrer.csv",delimiter=",",dtype='str')

In [140]:
a[:,3][][2:4]

array(["b'11:21:06'", "b'11:21:14'"], 
      dtype='<U17')

In [115]:
a[:,3][1][5:7]

'21'

In [116]:
a[:,3][1][8:10]

'04'

In [141]:
a[:,3][]

array(["b'time'", "b'11:21:04'", "b'11:21:06'", ..., "b'13:00:16'",
       "b'13:00:18'", "b'13:00:19'"], 
      dtype='<U17')

In [165]:
with open("datoscorrer.csv") as f:
    f.readline()
    content = f.readlines()

In [166]:
content.replace()

['-74.0783081055,4.6509594917,2604,11:21:04\n',
 '-74.0782623291,4.6510548592,2594,11:21:06\n',
 '-74.0782165527,4.6512036324,2572,11:21:14\n',
 '-74.0781860352,4.651330471,2565,11:21:18\n',
 '-74.0781784058,4.6514558792,2566,11:21:24\n',
 '-74.0781784058,4.6514558792,2566,11:21:26\n',
 '-74.0781784058,4.6514558792,2566,11:21:28\n',
 '-74.0781555176,4.6517424583,2567,11:21:34\n',
 '-74.0781402588,4.6518387794,2567,11:21:38\n',
 '-74.0781402588,4.6518387794,2567,11:21:40\n',
 '-74.0781402588,4.6518387794,2567,11:21:42\n',
 '-74.0781402588,4.6518387794,2567,11:21:44\n',
 '-74.0781402588,4.6518387794,2567,11:21:46\n',
 '-74.0781402588,4.6518387794,2567,11:21:48\n',
 '-74.0781402588,4.6518387794,2567,11:21:50\n',
 '-74.0781402588,4.6518387794,2567,11:21:52\n',
 '-74.0781402588,4.6518387794,2567,11:21:54\n',
 '-74.0781402588,4.6518387794,2567,11:21:56\n',
 '-74.0781402588,4.6518387794,2567,11:21:58\n',
 '-74.0781402588,4.6518387794,2567,11:22:00\n',
 '-74.0781402588,4.6518387794,2567,11:22:

In [155]:
b = time.strptime(a[:,3], "%H:%M:%S")

TypeError: strptime() argument 0 must be str, not <class 'numpy.ndarray'>

In [156]:
a[:,3]

array(["b'time'", "b'11:21:04'", "b'11:21:06'", ..., "b'13:00:16'",
       "b'13:00:18'", "b'13:00:19'"], 
      dtype='<U17')

In [151]:
datetime.timedelta(hours=a.tm_hour, minutes=a.tm_min, seconds=a.tm_sec).seconds

666

In [200]:
file = open("datoscorrer.csv")
reader = list(csv.reader(file))

In [230]:
tiempo = []
for i in range(1,len(reader)):
    actual = reader[i][3]
    a = time.strptime(actual, "%H:%M:%S")
    tiempo.append(datetime.timedelta(hours=a.tm_hour, minutes=a.tm_min, seconds=a.tm_sec).seconds)

In [213]:
reader[1][3]

'11:21:04'

In [217]:
reader[1][3]

'11:21:04'

In [227]:
a = time.strptime(reader[3][3], "%H:%M:%S")

In [228]:
a

time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=11, tm_min=21, tm_sec=14, tm_wday=0, tm_yday=1, tm_isdst=-1)

In [232]:
correr["time"] = np.array(tiempo)

In [233]:
correr["time"]

array([ 40864.,  40866.,  40874., ...,  46816.,  46818.,  46819.])

In [234]:
len(correr["time"])

1863